# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats to Segments and Google Analytics.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner.xcodeproj'

flutter_root = File.expand_path('..', __dir__)
require File.expand_path('flutter/pod_helpers.rb', flutter_root)

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.expand_path('..', __dir__)
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
